# Generated by Django 3.2.10 on 2022-01-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoFCM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, verbose_name='key')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='value')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='djangoFCM.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'notification argument',
                'verbose_name_plural': "notifications' arguments",
            },
        ),
        migrations.AddConstraint(
            model_name='notificationargument',
            constraint=models.UniqueConstraint(fields=('notification', 'key'), name='unique notification and key'),
        ),
    ]
