# Generated by Django 3.2.10 on 2022-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoFCM', '0002_auto_20220111_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='messaging_service',
            field=models.CharField(choices=[('F', 'Firebase Cloud Messaging'), ('H', 'Huawei Mobile Services')], default='F', max_length=1, verbose_name='messaging service'),
        ),
    ]
